#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: The Telephone Website lesson, macOS. Stage list mirrors setup.ps1.
# ──────────────────────────────────────────────────────────────────────────

if [[ "$(uname -s)" != "Darwin" ]]; then
  printf 'This is the macOS wizard. On Windows use setup.ps1 (see https://ai.reidsurmeier.wtf/telephone/).\n'
  exit 1
fi

mkdir -p "$HOME/.config/telephone-lesson"
ENV_FILE="$HOME/.config/telephone-lesson/setup.env"   # remembers non-secret answers between runs
TOTAL_STAGES=8

# _refresh_path: Homebrew on Apple Silicon lives in /opt/homebrew, which a fresh shell may not have yet.
_refresh_path() {
  [[ -x /opt/homebrew/bin/brew ]] && eval "$(/opt/homebrew/bin/brew shellenv)"
  [[ -x /usr/local/bin/brew ]]    && eval "$(/usr/local/bin/brew shellenv)"
  export PATH="$HOME/.local/bin:$PATH"
}
_refresh_path

banner "The Telephone Website: set up your Mac"

# ── 1. GitHub account ─────────────────────────────────────────────────────
stage "GitHub account"
say "GitHub is where your finished website will be hosted, for free."
if confirm "Do you already have a GitHub account?"; then
  note "Good. We'll sign in later."
else
  open_url "https://github.com/signup"
  step "Sign up with your school email. Pick a short username: it becomes part of your site's address."
  step "Verify the email GitHub sends you, then come back here."
  pause
fi
ask GITHUB_USERNAME "Type your GitHub username exactly:"
write_env GITHUB_USERNAME "$GITHUB_USERNAME"

# ── 2. Homebrew ───────────────────────────────────────────────────────────
stage "Homebrew (the Mac package installer)"
if command -v brew >/dev/null 2>&1; then
  note "Homebrew is already installed."
else
  say "Most Macs do not have Homebrew, the installer developer tools use. Installing it now."
  say "It asks for your Mac login password (nothing shows while you type), then downloads"
  say "Apple's command line tools. That can take five to ten minutes. Leave this window open."
  pause "Press Enter to install Homebrew"
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)" </dev/tty
  _refresh_path
  command -v brew >/dev/null 2>&1 || { warn "brew not found on PATH. Close this window, open a new Terminal, re-run the wizard."; exit 1; }
fi

# ── 3. git, gh, node ──────────────────────────────────────────────────────
stage "git, GitHub CLI, Node"
say "git tracks files, gh talks to GitHub, Node runs the skill installer."
brew install git gh node
_refresh_path
printf '  git %s · gh %s · node %s\n' "$(git --version | cut -d' ' -f3)" "$(gh --version | head -1 | cut -d' ' -f3)" "$(node --version)"
ask GIT_NAME "Your name, as it should appear on your work (e.g. Ada Lovelace):"
ask GIT_EMAIL "The email you used for GitHub:"
git config --global user.name "$GIT_NAME"
git config --global user.email "$GIT_EMAIL"
git config --global init.defaultBranch main
write_env GIT_NAME "$GIT_NAME"; write_env GIT_EMAIL "$GIT_EMAIL"

# ── 4. Codex ──────────────────────────────────────────────────────────────
stage "Codex (the coding agent)"
if command -v codex >/dev/null 2>&1; then
  note "Codex is already installed: $(codex --version 2>/dev/null)"
else
  say "Installing Codex with OpenAI's official installer."
  curl -fsSL https://chatgpt.com/codex/install.sh | sh
  _refresh_path
  command -v codex >/dev/null 2>&1 || { warn "codex not found on PATH. Open a new Terminal and re-run the wizard."; exit 1; }
  note "Installed $(codex --version)"
fi

# ── 5. ChatGPT sign-in ────────────────────────────────────────────────────
stage "Sign Codex in with ChatGPT"
say "Codex signs in with a ChatGPT account on the Plus plan (\$20/month). A free account will not work."
if confirm "Do you already have ChatGPT Plus?"; then :; else
  open_url "https://chatgpt.com/"
  step "Create an account, then upgrade to Plus (profile menu → Upgrade plan). Come back when it says Plus."
  pause
fi
say "A browser window will open. Choose 'Sign in with ChatGPT' and approve."
pause "Press Enter to start codex login"
codex login </dev/tty || warn "codex login did not finish. You can run 'codex login' yourself later."

# ── 6. GitHub token for the agent ─────────────────────────────────────────
stage "A GitHub token the agent can use"
say "The agent needs permission to create your repo and turn on GitHub Pages."
say "You'll make a fine-grained token that expires in 30 days."
open_url "https://github.com/settings/personal-access-tokens/new"
step "Token name: telephone-lesson.   Expiration: 30 days."
step "Repository access: All repositories."
step "Permissions → Repository permissions: set these three to Read and write:"
step "   Administration · Contents · Pages    (Metadata turns on by itself)"
step "Click Generate token, then copy it. It starts with github_pat_."
for attempt in 1 2 3; do
  ask_secret GITHUB_TOKEN "Paste the token (nothing will show as you paste):"
  GITHUB_TOKEN="${GITHUB_TOKEN//[[:space:]]/}"
  if [[ -n "$GITHUB_TOKEN" ]] && printf '%s' "$GITHUB_TOKEN" | gh auth login --with-token 2>/dev/null; then
    gh auth setup-git
    gh auth status 2>&1 | sed 's/^/  /'
    break
  fi
  warn "GitHub did not accept that token (try $attempt of 3)."
  say "Usual causes: the paste was empty or cut short, the token was copied before you clicked"
  say "Generate token, or it is a classic token instead of a fine-grained one."
  say "Go back to the GitHub tab, generate a fresh token, copy it, and paste again."
  [[ $attempt -eq 3 ]] && { warn "Still no luck. Ask for help, then run the wizard again; it skips what is done."; exit 1; }
done
unset GITHUB_TOKEN

# ── 7. Skills ─────────────────────────────────────────────────────────────
stage "Install the skills"
say "Skills are instruction files the agent reads. Two sets: Matt Pocock's (grill-me lives there) and this lesson's."
npx -y skills@latest add mattpocock/skills -a codex -g -y
npx -y skills@latest add Reid-Surmeier/ai-lessons -a codex -g -y

# ── 8. Check ──────────────────────────────────────────────────────────────
stage "Check everything"
ok=1
for c in git gh node codex; do
  if command -v "$c" >/dev/null 2>&1; then printf '  %s✓%s %s\n' "$GREEN" "$RESET" "$c"; else printf '  %s✗%s %s missing\n' "$RED" "$RESET" "$c"; ok=0; fi
done
gh auth status >/dev/null 2>&1 && printf '  %s✓%s signed in to GitHub as %s\n' "$GREEN" "$RESET" "$(gh api user --jq .login)" || { printf '  %s✗%s GitHub sign-in\n' "$RED" "$RESET"; ok=0; }
for s in grilling grill-me telephone; do
  [[ -f "$HOME/.agents/skills/$s/SKILL.md" ]] && printf '  %s✓%s skill %s\n' "$GREEN" "$RESET" "$s" || { printf '  %s✗%s skill %s\n' "$RED" "$RESET" "$s"; ok=0; }
done
(( ok )) || SKIPPED+=("something above is missing: re-run this wizard, it skips what is done")
say ""
say "Next: on lesson day, open Terminal and type   codex   then   \$telephone"

finish
